name: farm-flow-info
services:
  - name: api
    source_dir: .
    dockerfile_path: ./Dockerfile
    run_command: "node server.js"
    http_port: 8080
    instance_size_slug: basic-xxs
    instance_count: 1
    routes:
      - path: /


