const express = require("express");
const cors = require("cors");
const bodyParser = require("body-parser");
const weatherRoutes = require("./routes/weather");
const rainfallRoutes = require("./routes/rainfall");
const marketsRoutes = require("./routes/markets");
const alertsRoutes = require("./routes/alerts");
const locationsRoutes = require("./routes/locations");
const app = express();
const PORT = process.env.PORT || 8080;
app.use(cors());
app.use(bodyParser.json());
app.get("/health", (req, res) = res.json({ status: "ok" }); });
app.use("/weather", weatherRoutes);
app.use("/rainfall", rainfallRoutes);
app.use("/markets", marketsRoutes);
app.use("/alerts", alertsRoutes);
app.use("/locations", locationsRoutes);
app.listen(PORT, () = running on port ${PORT}`));
